//interleaving-arrays  https://www.codewars.com/kata/523d2e964680d1f749000135/train/javascript

//description: Create a function, that accepts an arbitrary number of arrays and returns a single array generated by alternately appending elements from the passed in arguments.



function interleave() {
  let bool = true, res = [], ct = 0;
  const arr = [...arguments];
  while (bool) {
    bool = false;
    arr.forEach(arr => {
      let arrValue;
      if (typeof arr[ct] !== 'undefined') {
        arrValue = arr[ct];
        bool = true;
      } else
        arrValue = null;
      res.push(arrValue);
    });
    ct++;
  }
  return res.splice(0, res.length - arguments.length);
}



console.log(interleave([1, 2, 3], ["c", "d", "e"]), [1, "c", 2, "d", 3, "e"]);
console.log(interleave([1, 2, 3], [4, 5]), [1, 4, 2, 5, 3, null]);
console.log(interleave([1, 2, 3], [4, 5, 6], [7, 8, 9]), [1, 4, 7, 2, 5, 8, 3, 6, 9]);
console.log(interleave([]), []);